// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function readEnv(key: string): string | undefined {
  // Explicit static checks for Vite string replacement
  if (key === 'VITE_SUPABASE_URL') return import.meta.env.VITE_SUPABASE_URL;
  if (key === 'VITE_SUPABASE_ANON_KEY') return import.meta.env.VITE_SUPABASE_ANON_KEY;
  if (key === 'VITE_SUPABASE_PUBLISHABLE_KEY') return import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  // Prefer Vite client-injected env (import.meta.env) when it's real.
  // In some TanStack Start + adapter setups, import.meta.env can be stripped, so we also check a global.
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const metaEnv = (import.meta as any)?.env as Record<string, string | undefined> | undefined;
    if (metaEnv && typeof metaEnv[key] === 'string' && metaEnv[key]) return metaEnv[key];
  } catch {
    // ignore
  }

  // Some Vite runtimes expose env on a global for SSR/client bridging.
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const viteEnv = (globalThis as any)?.__VITE_ENV__ as Record<string, string | undefined> | undefined;
    if (viteEnv && typeof viteEnv[key] === 'string' && viteEnv[key]) return viteEnv[key];
  } catch {
    // ignore
  }

  // Only fall back to process.env on the server.
  if (typeof window === 'undefined') {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const procEnv = (globalThis as any)?.process?.env as Record<string, string | undefined> | undefined;
      if (procEnv && typeof procEnv[key] === 'string' && procEnv[key]) return procEnv[key];
    } catch {
      // ignore
    }
  }

  return undefined;
}

function normalizeEnvValue(value: string | undefined): string | undefined {
  if (typeof value !== 'string') return undefined;
  const trimmed = value.trim();
  if (!trimmed) return undefined;

  // `.env` files often use quotes. Vite keeps the raw value (quotes included).
  // Supabase rejects quoted URLs/keys, so strip a single wrapping quote pair.
  const first = trimmed[0];
  const last = trimmed[trimmed.length - 1];
  if ((first === '"' && last === '"') || (first === "'" && last === "'")) {
    const unquoted = trimmed.slice(1, -1).trim();
    return unquoted || undefined;
  }

  return trimmed;
}

function createSupabaseClient() {
  // Debug helper: if env is unexpectedly missing at runtime, this makes it obvious in the browser console.
  // (Does not log the full key.)
  try {
    if (typeof window !== 'undefined') {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const metaEnv = (import.meta as any)?.env as Record<string, string | undefined> | undefined;
      const hasUrl = Boolean(metaEnv?.VITE_SUPABASE_URL);
      const hasAnon = Boolean(metaEnv?.VITE_SUPABASE_ANON_KEY);
      const hasPub = Boolean(metaEnv?.VITE_SUPABASE_PUBLISHABLE_KEY);
      // eslint-disable-next-line no-console
      console.debug('[supabase-env]', { hasUrl, hasAnon, hasPub });
    }
  } catch {
    // ignore
  }

  // Prefer Vite-prefixed vars.
  // In the browser, import.meta.env is the authoritative source.
  // Some bundlers/polyfills can define process.env in strange ways, so we avoid depending on it for client auth.
  const SUPABASE_URL = normalizeEnvValue(
    readEnv('VITE_SUPABASE_URL') ||
      readEnv('SUPABASE_URL') ||
      readEnv('SUPABASE_PUBLIC_URL')
  );
  const SUPABASE_PUBLISHABLE_KEY = normalizeEnvValue(
    readEnv('VITE_SUPABASE_PUBLISHABLE_KEY') ||
  readEnv('VITE_SUPABASE_ANON_KEY') ||
      readEnv('SUPABASE_PUBLISHABLE_KEY') ||
      readEnv('SUPABASE_ANON_KEY')
  );

  // During SSR build (or preview tooling) we don't want to crash the bundler just because env isn't present.
  // We'll return a client with empty values and let runtime usage surface a clear error when actually called.
  // Important: @supabase/supabase-js throws if url/key are empty.
  // If env is missing, surface a clear error (instead of a hydration cascade on /app).
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const hasUrl = Boolean(normalizeEnvValue(readEnv('VITE_SUPABASE_URL') || readEnv('SUPABASE_URL')));
    const hasKey = Boolean(
      normalizeEnvValue(
        readEnv('VITE_SUPABASE_PUBLISHABLE_KEY') ||
          readEnv('VITE_SUPABASE_ANON_KEY') ||
          readEnv('SUPABASE_PUBLISHABLE_KEY') ||
          readEnv('SUPABASE_ANON_KEY')
      )
    );
    throw new Error(
      `supabaseUrl is required. Missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY. (hasUrl=${hasUrl}, hasKey=${hasKey})`
    );
  }

  const url = SUPABASE_URL;
  const key = SUPABASE_PUBLISHABLE_KEY;

  const isBrowser = typeof window !== 'undefined';

  const client = createClient<Database>(url, key, {
    auth: {
      storage: isBrowser ? window.localStorage : undefined,
      storageKey: 'treegpt-auth',
      persistSession: true,
      autoRefreshToken: true,
    }
  });

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

